-- Comparing routes: one opted-in snapshot per student, and aggregates over them.
--
-- WHAT IS STORED: a random id made on the device, a school, a year, a coverage
-- figure, two arrays of course ids, and a planned test term. That is the whole
-- row.
--
-- WHAT IS NEVER STORED: no name, no email, no user id, no account link. A
-- signed-in student's snapshot is not joined to their user_state row and
-- cannot be — nothing here references auth.users. The id in this table is
-- generated by the browser and known only to that browser (and to whatever
-- devices the student's own account sync carries it to). Holding the id is
-- what owning the row means; there is no other key to it.
--
-- WHAT COMES BACK OUT: counts and aggregates, never rows. route_compare()
-- returns JSON, and below a group size of 20 it returns nothing but the count.
-- No query in this file can return one student's figures to anyone.

create table if not exists public.route_snapshot (
  id         uuid primary key,
  school     text        not null,
  year       text        not null,
  coverage   numeric(5,2) not null,
  done       text[]      not null default '{}',
  taking     text[]      not null default '{}',
  mcat_term  text,
  updated_at timestamptz not null default now()
);

-- The two shapes every aggregate reads by.
create index if not exists route_snapshot_school_year_idx on public.route_snapshot (school, year, updated_at);
create index if not exists route_snapshot_year_idx        on public.route_snapshot (year, updated_at);

-- No policies, on purpose — the same pattern as 0001. RLS on with zero policies
-- means the anon key can read and write exactly nothing directly: no select, no
-- insert, no update, no delete. Everything goes through the three functions
-- below, which are security definer and therefore the only path in or out.
--
-- This is what makes "the server never returns a row" true rather than
-- intended. A student with the publishable key cannot list the table, cannot
-- read a neighbour's coverage, and cannot find out whether a given id exists.
alter table public.route_snapshot enable row level security;

-- ── Writing ─────────────────────────────────────────────────────────────────
-- Insert or update the row with this id. Called by the browser with the anon
-- key, so it validates everything and trusts nothing.
--
-- KNOWN SCHOOLS ARE LISTED HERE. Adding a catalog to index.html means adding it
-- to the array below in a new migration — one line, and the cost of not letting
-- an arbitrary string create a phantom group.
create or replace function public.save_route_snapshot(
  p_id        uuid,
  p_school    text,
  p_year      text,
  p_coverage  numeric,
  p_done      text[],
  p_taking    text[],
  p_mcat_term text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last timestamptz;
begin
  if p_id is null then return; end if;

  -- Known school, known year. An unknown value is dropped rather than stored:
  -- a typo would otherwise make a group of one that never reaches 20 and never
  -- shows anything, which is a silent hole rather than a loud one.
  if p_school is null or p_school not in ('generic', 'byu', 'utah') then return; end if;
  if p_year   is null or p_year   not in ('freshman', 'sophomore', 'junior', 'senior') then return; end if;

  -- 77 is the ceiling, not 100: CARS is 23% of the exam and no class teaches
  -- it. A figure above that did not come from this app.
  if p_coverage is null or p_coverage < 0 or p_coverage > 77 then return; end if;

  -- A term, or nothing. "Not sure yet" is stored as null, which is also what a
  -- student who has not been asked has.
  if p_mcat_term is not null and p_mcat_term !~ '^[0-9]{4}-(spring|summer|fall)$' then return; end if;

  -- Arrays are bounded in both directions: how many, and how long each. Forty
  -- is past the largest catalog; thirty-two characters is past the longest
  -- course id. Without the second bound, forty entries is still unbounded.
  if coalesce(array_length(p_done, 1), 0)   > 40 then return; end if;
  if coalesce(array_length(p_taking, 1), 0) > 40 then return; end if;
  if exists (select 1 from unnest(coalesce(p_done, '{}')   ) c where c !~ '^[a-z0-9_-]{1,32}$') then return; end if;
  if exists (select 1 from unnest(coalesce(p_taking, '{}') ) c where c !~ '^[a-z0-9_-]{1,32}$') then return; end if;

  -- One write per id per thirty seconds. The client already debounces, so this
  -- is the floor underneath a client that stops: tapping a course on and off
  -- repeatedly cannot turn into a write per tap.
  select updated_at into v_last from public.route_snapshot where id = p_id;
  if v_last is not null and v_last > now() - interval '30 seconds' then return; end if;

  insert into public.route_snapshot (id, school, year, coverage, done, taking, mcat_term, updated_at)
  values (p_id, p_school, p_year, p_coverage,
          coalesce(p_done, '{}'), coalesce(p_taking, '{}'), p_mcat_term, now())
  on conflict (id) do update
    set school     = excluded.school,
        year       = excluded.year,
        coverage   = excluded.coverage,
        done       = excluded.done,
        taking     = excluded.taking,
        mcat_term  = excluded.mcat_term,
        updated_at = now();
end;
$$;

-- ── Removing ────────────────────────────────────────────────────────────────
-- "Remove my route" in Settings. The row goes; nothing is kept, not a tombstone
-- and not a count. The student's id is forgotten by the device at the same
-- moment, so this is the last chance anything has to reach the row.
create or replace function public.delete_route_snapshot(p_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.route_snapshot where id = p_id;
$$;

-- ── Reading ─────────────────────────────────────────────────────────────────
-- Aggregates for one school-and-year, and for that year at every school.
-- Returns JSON. Never returns a row, and below MIN_N returns nothing but the
-- count, so a group of three cannot be read back one student at a time.
--
-- Only snapshots updated since 1 August of the current academic year count. A
-- route last saved in a previous year describes a student who has since moved
-- up, and comparing this year's sophomores against last year's would put the
-- wrong people in the group.
create or replace function public.route_compare(
  p_school    text,
  p_year      text,
  p_mcat_term text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  min_n     constant int := 20;
  v_since   date;
  v_school  json;
  v_all     json;
begin
  if p_year is null or p_year not in ('freshman', 'sophomore', 'junior', 'senior') then
    return json_build_object('school', json_build_object('n', 0),
                             'all',    json_build_object('n', 0),
                             'min_n',  min_n);
  end if;

  -- 1 August of the academic year we are in: this year's if we are past
  -- August, last year's if we are not.
  v_since := make_date(
    case when extract(month from (now() at time zone 'utc')) >= 8
         then extract(year from (now() at time zone 'utc'))::int
         else extract(year from (now() at time zone 'utc'))::int - 1 end, 8, 1);

  -- ── The school group ──────────────────────────────────────────────────────
  -- One statement, built from CTEs rather than a temporary table. A temp table
  -- inside a security definer function is a hazard worth avoiding: it lives in
  -- pg_temp, which `set search_path = public` deliberately excludes, and a
  -- schema the caller can create objects in is the classic way to make a
  -- definer function run somebody else's code.
  with g as (
    select coverage, done, mcat_term
      from public.route_snapshot
     where school = p_school and year = p_year and updated_at >= v_since
  ), stats as (
    select count(*)::int as n,
           percentile_cont(0.25) within group (order by coverage) as p25,
           percentile_cont(0.50) within group (order by coverage) as p50,
           percentile_cont(0.75) within group (order by coverage) as p75
      from g
  ), above as (
    select count(*)::int as n from g, stats where g.coverage > stats.p50
  ), ahead as (
    -- What the students ahead have finished that this group's median has not
    -- reached yet. Half of them or more, so it reads as "most"; below that it
    -- is one cohort's habit rather than the shape of the year.
    select coalesce(json_agg(x order by x.share desc), '[]'::json) as j
      from (select c as course,
                   round(count(*)::numeric / nullif((select n from above), 0), 2) as share
              from g, stats, unnest(g.done) c
             where g.coverage > stats.p50
             group by c
            having count(*)::numeric / nullif((select n from above), 0) >= 0.5) x
  ), terms as (
    -- When they plan to sit it, "not sure" included, so the app can say what
    -- most of the group is doing rather than only what this student said.
    select coalesce(json_agg(x order by x.share desc), '[]'::json) as j
      from (select coalesce(mcat_term, 'unsure') as term,
                   round(count(*)::numeric / (select n from stats), 2) as share
              from g group by coalesce(mcat_term, 'unsure')) x
  ), tg as (
    -- The same group narrowed to the students sitting it when this one plans
    -- to. Its own floor: a subgroup of nine is still nine students, whatever
    -- the group around it counts.
    select count(*)::int as n,
           percentile_cont(0.25) within group (order by coverage) as p25,
           percentile_cont(0.50) within group (order by coverage) as p50,
           percentile_cont(0.75) within group (order by coverage) as p75
      from g
     where p_mcat_term is not null and mcat_term = p_mcat_term
  )
  select case when stats.n < min_n then json_build_object('n', stats.n)
              else json_build_object(
                'n',   stats.n,
                'p25', round(stats.p25),
                'p50', round(stats.p50),
                'p75', round(stats.p75),
                'ahead', (select j from ahead),
                'terms', (select j from terms),
                'term_group', case
                  when p_mcat_term is null then null
                  when (select n from tg) < min_n then json_build_object('n', (select n from tg))
                  else (select json_build_object('n', n, 'p25', round(p25),
                                                 'p50', round(p50), 'p75', round(p75)) from tg)
                end)
         end
    into v_school
    from stats;

  -- ── Every school, same year ───────────────────────────────────────────────
  -- No course list here: course ids mean different things in different
  -- catalogs, and "most juniors have finished chem481" is not a sentence a
  -- Utah student can act on. Coverage itself is comparable, which is the whole
  -- reason the three catalogs are checked against each other.
  with g as (
    select coverage from public.route_snapshot
     where year = p_year and updated_at >= v_since
  ), stats as (
    select count(*)::int as n,
           percentile_cont(0.25) within group (order by coverage) as p25,
           percentile_cont(0.50) within group (order by coverage) as p50,
           percentile_cont(0.75) within group (order by coverage) as p75
      from g
  )
  select case when n < min_n then json_build_object('n', n)
              else json_build_object('n', n, 'p25', round(p25),
                                     'p50', round(p50), 'p75', round(p75))
         end
    into v_all
    from stats;

  return json_build_object('school', v_school, 'all', v_all, 'min_n', min_n);
end;
$$;

-- These three are the opposite case from 0001's: they are meant to be called
-- from a browser holding the publishable anon key, because a snapshot has no
-- account behind it and a comparison is available to a student who has never
-- signed in. Everything they will accept is validated above, and the only
-- thing they return is an aggregate.
grant execute on function public.save_route_snapshot(uuid, text, text, numeric, text[], text[], text) to anon, authenticated;
grant execute on function public.delete_route_snapshot(uuid)                                          to anon, authenticated;
grant execute on function public.route_compare(text, text, text)                                      to anon, authenticated;

-- Direct table access stays shut for every key but the service role, which
-- bypasses RLS and is never in a browser.
revoke all on table public.route_snapshot from anon, authenticated;
